export const SET_CLIENTE = 'SET_CLIENTE';
export const EXCLUIR_CLIENTE = 'EXCLUIR_CLIENTE';
export const DOWNLOAD_CLIENTE = 'DOWNLOAD_CLIENTE';
export const EDITAR_CLIENTE = 'EDITAR_CLIENTE';
export const UPLOAD_CLIENTE = 'UPLOAD_CLIENTE';
